baseURL = "https://lijomjose.github.io/"
title = "Lijo M. Jose"
theme = "PaperMod"

[params]
author = "Lijo M. Jose"
description = "Researcher in Graph Theory and Algorithms | Teacher(Assitant Professor) | Manipal Instutute of Technology Bangalore | "
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
defaultTheme = "auto"

[menu]

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 4

[[menu.main]]
identifier = "research"
name = "Research"
url = "/research/"
weight = 1

[[menu.main]]
identifier = "teaching"
name = "Teaching"
url = "/teaching/"
weight = 2

[[menu.main]]
identifier = "articles"
name = "Articles"
url = "/posts/"
weight = 3
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
